sonar.projectKey=maryhelenab_sonar-project-properties
sonar.organization=maryhelenab

sonar.sources=simple_proj
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/env/**,**/__pycache__/**,**/migrations/**,**/*.pyc,**/db.sqlite3
